//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventStore.Core.Sql.Sqlite {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqliteStatements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqliteStatements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventStore.Core.Sql.Sqlite.SqliteStatements", typeof(SqliteStatements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Events] VALUES (@id, @version{0}, @created, @type{0}, @payload{0});.
        /// </summary>
        internal static string InsertEvent {
            get {
                return ResourceManager.GetString("InsertEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT
        ///    INTO [Aggregates]
        ///  SELECT @id, @version, 0, @created, @type
        ///   WHERE @version = 0;
        ///
        ///{0}
        ///
        ///INSERT
        ///  INTO [Snapshots]
        ///SELECT @id, @version, @created, @snapshot_type, @payload
        /// WHERE @payload IS NOT NULL
        ///   AND NOT EXISTS -- snapshots don&apos;t need to be overwritten
        ///     ( SELECT *
        ///         FROM [Snapshots]
        ///        WHERE [Id] = @id
        ///          AND [Version] = @version );
        ///
        ///UPDATE [Aggregates]
        ///   SET [Version] = @version,
        ///       [Snapshot] = CASE WHEN @payload IS NOT NULL THEN @version E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertEvents {
            get {
                return ResourceManager.GetString("InsertEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Payload], [RuntimeType]
        ///  FROM [Events]
        /// WHERE [Id] = @id
        ///   AND [Version] &gt; (SELECT [Snapshot] FROM [Aggregates] WHERE [Id] = @id)
        /// ORDER BY [Version];
        /// 
        ///SELECT [Payload],
        ///       [RuntimeType],
        ///       [Version]
        ///  FROM [Snapshots]
        /// WHERE [Id] = @id
        /// ORDER BY [Version] DESC
        /// LIMIT 1;.
        /// </summary>
        internal static string SelectEvents {
            get {
                return ResourceManager.GetString("SelectEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Payload], [RuntimeType]
        ///  FROM [Events]
        /// WHERE [Id] = @id
        ///   AND [Version] &gt;= @version
        /// ORDER BY [Version];.
        /// </summary>
        internal static string SelectEventsWhere {
            get {
                return ResourceManager.GetString("SelectEventsWhere", resourceCulture);
            }
        }
    }
}
