//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventStore.Persistence.SqlPersistence {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventStore.Persistence.SqlPersistence.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection could not be created for the specified named connection..
        /// </summary>
        internal static string BadConnectionName {
            get {
                return ResourceManager.GetString("BadConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring connections: master &apos;{0}&apos;; replica &apos;{1}&apos;, shards: {2}..
        /// </summary>
        internal static string ConfiguringConnections {
            get {
                return ResourceManager.GetString("ConfiguringConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find connection name &apos;{0}&apos; in the configuration file..
        /// </summary>
        internal static string ConnectionNotFound {
            get {
                return ResourceManager.GetString("ConnectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered DB provider factory settings for &apos;{0}&apos;, using &apos;{1}&apos;..
        /// </summary>
        internal static string DiscoveredConnectionProvider {
            get {
                return ResourceManager.GetString("DiscoveredConnectionProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovering connection settings for &apos;{0}&apos;..
        /// </summary>
        internal static string DiscoveringConnectionSettings {
            get {
                return ResourceManager.GetString("DiscoveringConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedding sharding key into connection string for &apos;{0}&apos;..
        /// </summary>
        internal static string EmbeddingShardKey {
            get {
                return ResourceManager.GetString("EmbeddingShardKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the required attribute &apos;connection string&apos; on the connection name &apos;{0}&apos; in the configuration file..
        /// </summary>
        internal static string MissingConnectionString {
            get {
                return ResourceManager.GetString("MissingConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the required attribute &apos;providerName&apos; on the connection name &apos;{0}&apos; in the configuration file..
        /// </summary>
        internal static string MissingProviderName {
            get {
                return ResourceManager.GetString("MissingProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open connection &apos;{0}&apos;..
        /// </summary>
        internal static string OpenFailed {
            get {
                return ResourceManager.GetString("OpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening connection &apos;{0}&apos;..
        /// </summary>
        internal static string OpeningConnection {
            get {
                return ResourceManager.GetString("OpeningConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening master connection &apos;{0}&apos;.
        /// </summary>
        internal static string OpeningMasterConnection {
            get {
                return ResourceManager.GetString("OpeningMasterConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening replica connection &apos;{0}&apos;..
        /// </summary>
        internal static string OpeningReplicaConnection {
            get {
                return ResourceManager.GetString("OpeningReplicaConnection", resourceCulture);
            }
        }
    }
}
