//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventStore.Core.Sql.MsSqlServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsSqlServerStatements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsSqlServerStatements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventStore.Core.Sql.MsSqlServer.MsSqlServerStatements", typeof(MsSqlServerStatements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT @version = @version + 1;
        ///INSERT
        ///  INTO [dbo].[Events]
        ///SELECT @id, @version, @type{0}, @created, @payload{0};.
        /// </summary>
        internal static string InsertEvent {
            get {
                return ResourceManager.GetString("InsertEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT
        ///    INTO [dbo].[Aggregates]
        ///  SELECT @id, @version, 0, @type, @created
        ///   WHERE @version = 0;
        ///
        ///{0}
        ///
        ///UPDATE [dbo].[Aggregates]
        ///   SET [Version] = @version
        /// WHERE [AggregateId] = @id;.
        /// </summary>
        internal static string InsertEvents {
            get {
                return ResourceManager.GetString("InsertEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT
        ///  INTO [dbo].[Snapshots]
        ///SELECT @id, @version, @type, @created, @payload
        /// WHERE NOT EXISTS
        ///     ( SELECT *
        ///         FROM [dbo].[Snapshots]
        ///        WHERE [AggregateId] = @id
        ///          AND [Version] = @version );.
        /// </summary>
        internal static string InsertSnapshot {
            get {
                return ResourceManager.GetString("InsertSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Payload], [RuntimeType]
        ///    FROM [dbo].[Events]
        ///   WHERE [AggregateId] = @id
        ///     AND [Version] &gt;= @version;.
        /// </summary>
        internal static string SelectEvents {
            get {
                return ResourceManager.GetString("SelectEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 [Payload], [RuntimeType]
        ///    FROM [dbo].[Events]
        ///   WHERE [AggregateId] = @id
        ///   ORDER BY [Version];.
        /// </summary>
        internal static string SelectSnapshot {
            get {
                return ResourceManager.GetString("SelectSnapshot", resourceCulture);
            }
        }
    }
}
