//-----------------------------------------------------------------------
// <copyright file="VersionAssemblyInfo.cs" company="Exact Wave, LLC">
//     Copyright (c) Jonathan Oliver. All rights reserved.
// </copyright>
// <author>Rake Build Script</author>
//----------------------------------

using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
//// [assembly: AssemblyInformationalVersion("1.0.0.0 Alpha")]