//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventStore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventStore.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding commit &apos;{0} with {1} events to stream &apos;{2}&apos;..
        /// </summary>
        internal static string AddingCommitsToStream {
            get {
                return ResourceManager.GetString("AddingCommitsToStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a snapshot for stream &apos;{0}&apos; at revision &apos;{1}&apos;..
        /// </summary>
        internal static string AddingSnapshot {
            get {
                return ResourceManager.GetString("AddingSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object has already been disposed..
        /// </summary>
        internal static string AlreadyDisposed {
            get {
                return ResourceManager.GetString("AlreadyDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appending uncommitted event to stream &apos;{0}&apos;.
        /// </summary>
        internal static string AppendingUncommittedToStream {
            get {
                return ResourceManager.GetString("AppendingUncommittedToStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to append commit &apos;{0}&apos; to stream &apos;{1}&apos; at position &apos;{2}&apos;..
        /// </summary>
        internal static string AttemptingToCommit {
            get {
                return ResourceManager.GetString("AttemptingToCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to commit all changes on stream &apos;{0}&apos; to the underlying store..
        /// </summary>
        internal static string AttemptingToCommitChanges {
            get {
                return ResourceManager.GetString("AttemptingToCommitChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building a commit attempt &apos;{0}&apos; on stream &apos;{1}&apos;..
        /// </summary>
        internal static string BuildingCommitAttempt {
            get {
                return ResourceManager.GetString("BuildingCommitAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing all uncommitted changes on stream &apos;{0}&apos;..
        /// </summary>
        internal static string ClearingUncommittedChanges {
            get {
                return ResourceManager.GetString("ClearingUncommittedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit attempt failed one or more integrity checks..
        /// </summary>
        internal static string CommitAttemptFailedIntegrityChecks {
            get {
                return ResourceManager.GetString("CommitAttemptFailedIntegrityChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline hook of type &apos;{0}&apos; rejected attempt &apos;{1}&apos;..
        /// </summary>
        internal static string CommitRejectedByPipelineHook {
            get {
                return ResourceManager.GetString("CommitRejectedByPipelineHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The commit must be uniquely identified..
        /// </summary>
        internal static string CommitsMustBeUniquelyIdentified {
            get {
                return ResourceManager.GetString("CommitsMustBeUniquelyIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing attempt &apos;{0}&apos; to the underlying persistence engine..
        /// </summary>
        internal static string CommittingAttempt {
            get {
                return ResourceManager.GetString("CommittingAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating stream &apos;{0}&apos;..
        /// </summary>
        internal static string CreatingStream {
            get {
                return ResourceManager.GetString("CreatingStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposing engine..
        /// </summary>
        internal static string DisposingEngine {
            get {
                return ResourceManager.GetString("DisposingEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all commits for stream &apos;{0}&apos; between &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string GettingAllCommitsFromRevision {
            get {
                return ResourceManager.GetString("GettingAllCommitsFromRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all commits from &apos;{0}&apos; forward..
        /// </summary>
        internal static string GettingAllCommitsFromTime {
            get {
                return ResourceManager.GetString("GettingAllCommitsFromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting the most recent snapshot for stream &apos;{0}&apos; on/since revision &apos;{1}&apos;..
        /// </summary>
        internal static string GettingSnapshotForStream {
            get {
                return ResourceManager.GetString("GettingSnapshotForStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting the set of all streams to be snapshot which exceed {0} revisions without a snapshot..
        /// </summary>
        internal static string GettingStreamsToSnapshot {
            get {
                return ResourceManager.GetString("GettingStreamsToSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting undispatched commits from persistence engine..
        /// </summary>
        internal static string GettingUndispatchedCommits {
            get {
                return ResourceManager.GetString("GettingUndispatchedCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring some events on commit &apos;{0}&apos; of stream &apos;{1}&apos; because they starting before revision {2}..
        /// </summary>
        internal static string IgnoringBeforeRevision {
            get {
                return ResourceManager.GetString("IgnoringBeforeRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring some events on commit &apos;{0}&apos; of stream &apos;{1}&apos; because they go beyond revision {2}..
        /// </summary>
        internal static string IgnoringBeyondRevision {
            get {
                return ResourceManager.GetString("IgnoringBeyondRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing engine..
        /// </summary>
        internal static string InitializingEngine {
            get {
                return ResourceManager.GetString("InitializingEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing persistence engine..
        /// </summary>
        internal static string InitializingPersistence {
            get {
                return ResourceManager.GetString("InitializingPersistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing commit &apos;{0}&apos; to post-commit hook of type &apos;{1}&apos;..
        /// </summary>
        internal static string InvokingPostCommitPipelineHooks {
            get {
                return ResourceManager.GetString("InvokingPostCommitPipelineHooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing commit &apos;{0}&apos; to pre-commit hook of type &apos;{1}&apos;..
        /// </summary>
        internal static string InvokingPreCommitHooks {
            get {
                return ResourceManager.GetString("InvokingPreCommitHooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking commit &apos;{0}&apos; as dispatched..
        /// </summary>
        internal static string MarkingAsDispatched {
            get {
                return ResourceManager.GetString("MarkingAsDispatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking commit &apos;{0}&apos; as dispatched..
        /// </summary>
        internal static string MarkingCommitAsDispatched {
            get {
                return ResourceManager.GetString("MarkingCommitAsDispatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no outstanding changes to be committed stream &apos;{0}&apos;..
        /// </summary>
        internal static string NoChangesToCommit {
            get {
                return ResourceManager.GetString("NoChangesToCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No other commits have been discovered that conflict for stream &apos;{0}&apos;..
        /// </summary>
        internal static string NoConflicts {
            get {
                return ResourceManager.GetString("NoConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging all commits on stream &apos;{0}&apos; from tracking..
        /// </summary>
        internal static string NoLongerTrackingStream {
            get {
                return ResourceManager.GetString("NoLongerTrackingStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream revision must be a positive number..
        /// </summary>
        internal static string NonPositiveRevisionNumber {
            get {
                return ResourceManager.GetString("NonPositiveRevisionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The commit sequence must be a positive number..
        /// </summary>
        internal static string NonPositiveSequenceNumber {
            get {
                return ResourceManager.GetString("NonPositiveSequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening stream &apos;{0}&apos; between revisions {1} and {2}..
        /// </summary>
        internal static string OpeningStreamAtRevision {
            get {
                return ResourceManager.GetString("OpeningStreamAtRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening stream &apos;{0}&apos; with snapshot at {1} up to revision {2}..
        /// </summary>
        internal static string OpeningStreamWithSnapshot {
            get {
                return ResourceManager.GetString("OpeningStreamWithSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying that no other commits have succeed on the stream &apos;{0}&apos;..
        /// </summary>
        internal static string OptimisticConcurrencyCheck {
            get {
                return ResourceManager.GetString("OptimisticConcurrencyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing attempt &apos;{0}&apos; on stream &apos;{1}&apos; to the underlying store..
        /// </summary>
        internal static string PersistingCommit {
            get {
                return ResourceManager.GetString("PersistingCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more pipeline hooks filtered out the commit..
        /// </summary>
        internal static string PipelineHookFilteredCommit {
            get {
                return ResourceManager.GetString("PipelineHookFilteredCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline hook of type &apos;{0}&apos; skipped over commit &apos;{1}&apos;..
        /// </summary>
        internal static string PipelineHookSkippedCommit {
            get {
                return ResourceManager.GetString("PipelineHookSkippedCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing commit &apos;{0}&apos; to message publisher..
        /// </summary>
        internal static string PublishingCommit {
            get {
                return ResourceManager.GetString("PublishingCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing message to /dev/null..
        /// </summary>
        internal static string PublishingToDevNull {
            get {
                return ResourceManager.GetString("PublishingToDevNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging all data from storage..
        /// </summary>
        internal static string PurgingStore {
            get {
                return ResourceManager.GetString("PurgingStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection is read only and cannot be modified..
        /// </summary>
        internal static string ReadOnlyCollection {
            get {
                return ResourceManager.GetString("ReadOnlyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving all {0} undispatched commits..
        /// </summary>
        internal static string RetrievingUndispatchedCommits {
            get {
                return ResourceManager.GetString("RetrievingUndispatchedCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stream revision must always be greater than or equal to the commit sequence..
        /// </summary>
        internal static string RevisionTooSmall {
            get {
                return ResourceManager.GetString("RevisionTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling commit &apos;{0}&apos; for delivery..
        /// </summary>
        internal static string SchedulingDelivery {
            get {
                return ResourceManager.GetString("SchedulingDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down dispatcher..
        /// </summary>
        internal static string ShuttingDownDispatcher {
            get {
                return ResourceManager.GetString("ShuttingDownDispatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down publisher..
        /// </summary>
        internal static string ShuttingDownPublisher {
            get {
                return ResourceManager.GetString("ShuttingDownPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down event store..
        /// </summary>
        internal static string ShuttingDownStore {
            get {
                return ResourceManager.GetString("ShuttingDownStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting dispatcher.
        /// </summary>
        internal static string StartingDispatcher {
            get {
                return ResourceManager.GetString("StartingDispatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping dispatcher.
        /// </summary>
        internal static string StoppingDispatcher {
            get {
                return ResourceManager.GetString("StoppingDispatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking commit {0} on stream &apos;{1}&apos;..
        /// </summary>
        internal static string TrackingCommit {
            get {
                return ResourceManager.GetString("TrackingCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking up to {0} streams..
        /// </summary>
        internal static string TrackingStreams {
            get {
                return ResourceManager.GetString("TrackingStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying stream &apos;{0}&apos; has changed since the last known commit, refreshing the stream..
        /// </summary>
        internal static string UnderlyingStreamHasChanged {
            get {
                return ResourceManager.GetString("UnderlyingStreamHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating stream head for stream &apos;{0}&apos;..
        /// </summary>
        internal static string UpdatingStreamHead {
            get {
                return ResourceManager.GetString("UpdatingStreamHead", resourceCulture);
            }
        }
    }
}
